-- ============================================================
-- Migration: 004_fix_all_recipe_bottle_ids.sql
-- Description: Fix all broken bottle IDs in Cocktail.recipe JSON
--              and insert missing bottle entries.
-- Generated: 2026-03-09
-- ============================================================

-- ── Step 1: Insert missing bottles ─────────────────────────────────────

INSERT INTO Bottle (id, name, category, type, alcoholContent, sugarContent, acidity, createdAt, updatedAt)
  SELECT 'fix_coffee_liqueur_001', 'Coffee Liqueur (Kahlua)', 'Liqueur', 'Liqueur', 20, 45, 0, NOW(), NOW()
  WHERE NOT EXISTS (SELECT 1 FROM Bottle WHERE id = 'fix_coffee_liqueur_001');

INSERT INTO Bottle (id, name, category, type, alcoholContent, sugarContent, acidity, createdAt, updatedAt)
  SELECT 'fix_angostura_bitters_01', 'Angostura Bitters', 'Bitters', 'Bitters', 44.7, 0, 0, NOW(), NOW()
  WHERE NOT EXISTS (SELECT 1 FROM Bottle WHERE id = 'fix_angostura_bitters_01');

INSERT INTO Bottle (id, name, category, type, alcoholContent, sugarContent, acidity, createdAt, updatedAt)
  SELECT 'fix_creme_violette_001', 'Crème de Violette', 'Liqueur', 'Liqueur', 16, 30, 0, NOW(), NOW()
  WHERE NOT EXISTS (SELECT 1 FROM Bottle WHERE id = 'fix_creme_violette_001');

INSERT INTO Bottle (id, name, category, type, alcoholContent, sugarContent, acidity, createdAt, updatedAt)
  SELECT 'fix_apricot_liqueur_001', 'Apricot Liqueur', 'Liqueur', 'Liqueur', 25, 25, 0, NOW(), NOW()
  WHERE NOT EXISTS (SELECT 1 FROM Bottle WHERE id = 'fix_apricot_liqueur_001');

INSERT INTO Bottle (id, name, category, type, alcoholContent, sugarContent, acidity, createdAt, updatedAt)
  SELECT 'fix_coconut_cream_001', 'Coconut Cream', 'Syrup', 'Syrup', 0, 15, 0, NOW(), NOW()
  WHERE NOT EXISTS (SELECT 1 FROM Bottle WHERE id = 'fix_coconut_cream_001');

INSERT INTO Bottle (id, name, category, type, alcoholContent, sugarContent, acidity, createdAt, updatedAt)
  SELECT 'fix_cream_001', 'Cream', 'Syrup', 'Syrup', 0, 3, 0, NOW(), NOW()
  WHERE NOT EXISTS (SELECT 1 FROM Bottle WHERE id = 'fix_cream_001');

INSERT INTO Bottle (id, name, category, type, alcoholContent, sugarContent, acidity, createdAt, updatedAt)
  SELECT 'fix_benedictine_001', 'Benedictine', 'Liqueur', 'Liqueur', 40, 28, 0, NOW(), NOW()
  WHERE NOT EXISTS (SELECT 1 FROM Bottle WHERE id = 'fix_benedictine_001');

-- ── Step 2: Update Cocktail.recipe with corrected bottle IDs ─────────

UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3o700dyo1nwfoyh7as3","name":"Amaretto","amount":1.5,"pourOrder":1},{"bottleId":"cmmgep3jr000io1nw2k85pm7x","name":"Bourbon","amount":0.75,"pourOrder":1},{"bottleId":"cmmgep3pp00ioo1nwgfpska2u","name":"Lemon Juice","amount":1,"pourOrder":2},{"bottleId":"cmmgep3qv00mgo1nwc960yavi","name":"Simple Syrup","amount":0.25,"pourOrder":2}]' WHERE id = 'cmmhaha9j000111spt4rue5ce'; -- Amaretto Sour
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3om00f8o1nwo3o2vrgk","name":"Aperol","amount":2,"pourOrder":1},{"bottleId":"cmmgep3p500gyo1nw9pw51cyd","name":"Prosecco","amount":3,"pourOrder":1},{"bottleId":"cmmgep3qs00m6o1nwtg9vgg41","name":"Soda Water","amount":1,"pourOrder":2}]' WHERE id = 'cmma2lo780001124r0gbjaluc'; -- Aperol Spritz
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3je0001o1nwu7e8off1","name":"Gin","amount":2,"pourOrder":1},{"bottleId":"cmmgep3ob00eao1nwu689hpe8","name":"Maraschino Liqueur","amount":0.5,"pourOrder":1},{"bottleId":"cmmgep3pp00ioo1nwgfpska2u","name":"Lemon Juice","amount":0.5,"pourOrder":1},{"bottleId":"fix_creme_violette_001","name":"Crème de Violette","amount":0.25,"pourOrder":1}]' WHERE id = 'cmma3nay4000csp88zj2tpp22'; -- Aviation
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3ji0005o1nw11qwqv97","name":"Vodka","amount":2,"pourOrder":1},{"bottleId":"cmmgep3nz00dco1nwwr7os5qm","name":"Coffee Liqueur","amount":1,"pourOrder":1}]' WHERE id = 'cmma5uuft0001hjw6iqkrdxne'; -- Black Russian
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3jr000io1nw2k85pm7x","name":"Bourbon","amount":1,"pourOrder":1},{"bottleId":"cmmgep3ol00f6o1nwinexd6jf","name":"Campari","amount":1,"pourOrder":1},{"bottleId":"cmmgep3mi0096o1nwz7p1ekwb","name":"Sweet Vermouth","amount":1,"pourOrder":1}]' WHERE id = 'cmma2ktl60001io243l02otjh'; -- Boulevardier
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3je0001o1nwu7e8off1","name":"Gin","amount":1.5,"pourOrder":1},{"bottleId":"cmmgep3pp00ioo1nwgfpska2u","name":"Lemon Juice","amount":0.75,"pourOrder":2},{"bottleId":"cmmgep3qv00mgo1nwc960yavi","name":"Simple Syrup","amount":0.5,"pourOrder":2},{"bottleId":"cmmhaha3m00001ev56h2us4oi","name":"Crème de Mûre","amount":0.5,"pourOrder":3}]' WHERE id = 'cmmhaha3p00021ev5tq6foo9s'; -- Bramble
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3ly007eo1nwm1qruxyl","name":"Cachaça","amount":2,"pourOrder":1}]' WHERE id = 'cmma2ktn00001z4be8h7y0uj3'; -- Caipirinha
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3je0001o1nwu7e8off1","name":"Gin","amount":2,"pourOrder":1},{"bottleId":"cmmgep3pp00ioo1nwgfpska2u","name":"Lemon Juice","amount":1,"pourOrder":1},{"bottleId":"fix_raspberry_syrup_001","name":"Raspberry Syrup","amount":0.75,"pourOrder":1}]' WHERE id = 'cmma2i83800028tdjkgit3z0f'; -- Clover Club
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3ji0005o1nw11qwqv97","name":"Vodka","amount":1.5,"pourOrder":1},{"bottleId":"cmmgep3nx00d4o1nwgbkk3giv","name":"Triple Sec","amount":1,"pourOrder":1},{"bottleId":"cmmgep3px00jco1nw8lna1no7","name":"Cranberry Juice","amount":1,"pourOrder":1},{"bottleId":"cmmgep3pr00iwo1nw8lhyzmpp","name":"Lime Juice","amount":0.5,"pourOrder":1}]' WHERE id = 'cmma2lod90001g4q8klcodzaf'; -- Cosmopolitan
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3lc005io1nw328zeizv","name":"White Rum","amount":2,"pourOrder":1},{"bottleId":"cmmgep3pr00iwo1nw8lhyzmpp","name":"Lime Juice","amount":0.5,"pourOrder":1},{"bottleId":"cmmgep3qa00kko1nwo0skn0bv","name":"Cola","amount":0.5,"pourOrder":2}]' WHERE id = 'cmma2ktsx0001hr09oqqublg6'; -- Cuba Libre
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3lc005io1nw328zeizv","name":"White Rum","amount":2,"pourOrder":1},{"bottleId":"cmmgep3pr00iwo1nw8lhyzmpp","name":"Lime Juice","amount":1,"pourOrder":1}]' WHERE id = 'cmma2loge0001emvpfwvmtsie'; -- Daiquiri
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3lj0064o1nwcank12o2","name":"Dark Rum","amount":2,"pourOrder":2},{"bottleId":"cmmgep3pr00iwo1nw8lhyzmpp","name":"Lime Juice","amount":0.5,"pourOrder":1}]' WHERE id = 'cmma2ktvw0001nsmke9o1gsam'; -- Dark ’n’ Stormy
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3ji0005o1nw11qwqv97","name":"Vodka","amount":1.5,"pourOrder":1},{"bottleId":"cmmgep3nz00dco1nwwr7os5qm","name":"Coffee Liqueur","amount":1,"pourOrder":1}]' WHERE id = 'cmma2loje0001yyiv4qvq5jmp'; -- Espresso Martini
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3je0001o1nwu7e8off1","name":"Gin","amount":1,"pourOrder":1},{"bottleId":"cmmgep3pp00ioo1nwgfpska2u","name":"Lemon Juice","amount":0.5,"pourOrder":1},{"bottleId":"cmmgep3p200gmo1nwz3zuw5d5","name":"Champagne","amount":2,"pourOrder":2}]' WHERE id = 'cmma2lokw0001ns00tgep1dzj'; -- French 75
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3je0001o1nwu7e8off1","name":"Gin","amount":2,"pourOrder":1},{"bottleId":"cmmgep3pr00iwo1nw8lhyzmpp","name":"Lime Juice","amount":1,"pourOrder":1}]' WHERE id = 'cmma2lomg0001gialim6p5diy'; -- Gimlet
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3jz0016o1nw91d4gbjl","name":"Scotch Single Malt","amount":2,"pourOrder":1},{"bottleId":"cmmgep3o700dyo1nwfoyh7as3","name":"Amaretto","amount":1,"pourOrder":1}]' WHERE id = 'cmma60os50002v1renm2smwk3'; -- Godfather
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3lc005io1nw328zeizv","name":"White Rum","amount":2,"pourOrder":1},{"bottleId":"cmmgep3lj0064o1nwcank12o2","name":"Dark Rum","amount":1,"pourOrder":1},{"bottleId":"fix_passion_fruit_syrup01","name":"Passion Fruit Syrup","amount":1,"pourOrder":1},{"bottleId":"cmmgep3pm00ieo1nwl3fd8emz","name":"Orange Juice","amount":1,"pourOrder":1},{"bottleId":"cmmgep3pr00iwo1nw8lhyzmpp","name":"Lime Juice","amount":0.5,"pourOrder":1},{"bottleId":"cmmgep3qv00mgo1nwc960yavi","name":"Simple Syrup","amount":0.5,"pourOrder":1}]' WHERE id = 'cmma4kkol0002l1z361h3yd8m'; -- Hurricane
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3oa00e8o1nwt39qicg1","name":"Crème de Cassis","amount":0.5,"pourOrder":1},{"bottleId":"cmmgep3p200gmo1nwz3zuw5d5","name":"Champagne","amount":4,"pourOrder":2}]' WHERE id = 'cmma675430004busojgq5vdvo'; -- Kir Royale
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3je0001o1nwu7e8off1","name":"Gin","amount":0.75,"pourOrder":1},{"bottleId":"cmmhaha6b0000txph3373eliv","name":"Green Chartreuse","amount":0.75,"pourOrder":1},{"bottleId":"cmmgep3ob00eao1nwu689hpe8","name":"Maraschino Liqueur","amount":0.75,"pourOrder":1},{"bottleId":"cmmgep3pr00iwo1nw8lhyzmpp","name":"Lime Juice","amount":0.75,"pourOrder":2}]' WHERE id = 'cmmhaha6e0002txphpsnuf7c5'; -- Last Word
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3kc002co1nwtkpunj35","name":"Rye Whiskey","amount":2,"pourOrder":1},{"bottleId":"cmmgep3mi0096o1nwz7p1ekwb","name":"Sweet Vermouth","amount":0.75,"pourOrder":1},{"bottleId":"cmmgep3re00o4o1nwwvrma14j","name":"Angostura Aromatic Bitters","amount":0.031,"pourOrder":1}]' WHERE id = 'cmma2lony0001ekxw2iwzdc6w'; -- Manhattan
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3jg0003o1nw2wl9z27o","name":"Tequila","amount":2,"pourOrder":1},{"bottleId":"cmmgep3nx00d4o1nwgbkk3giv","name":"Triple Sec","amount":1,"pourOrder":1},{"bottleId":"cmmgep3pr00iwo1nw8lhyzmpp","name":"Lime Juice","amount":1,"pourOrder":1}]' WHERE id = 'cmma2lopj0001e1vqe3g0de9y'; -- Margarita
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3je0001o1nwu7e8off1","name":"Gin","amount":2.5,"pourOrder":1},{"bottleId":"cmmgep3mf008wo1nwbjxod65s","name":"Dry Vermouth","amount":0.5,"pourOrder":1}]' WHERE id = 'cmma2ku4300012pnzsi26dt7f'; -- Martini
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3jr000io1nw2k85pm7x","name":"Bourbon","amount":1.5,"pourOrder":1},{"bottleId":"cmmgep3jn000co1nwr864ucvh","name":"Absinthe","amount":0.1,"pourOrder":1},{"bottleId":"cmmgep3pp00ioo1nwgfpska2u","name":"Lemon Juice","amount":0.75,"pourOrder":2},{"bottleId":"cmmgep3qx00moo1nwitbb1r9z","name":"Grenadine","amount":0.5,"pourOrder":2}]' WHERE id = 'cmmhahab20001pscihy2zf0w6'; -- Millionaire
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3jr000io1nw2k85pm7x","name":"Bourbon","amount":2,"pourOrder":1}]' WHERE id = 'cmma2ku5k00012mi3lcxdizm0'; -- Mint Julep
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3lc005io1nw328zeizv","name":"White Rum","amount":2,"pourOrder":1},{"bottleId":"cmmgep3pr00iwo1nw8lhyzmpp","name":"Lime Juice","amount":1,"pourOrder":1},{"bottleId":"cmmgep3qs00m6o1nwtg9vgg41","name":"Soda Water","amount":1,"pourOrder":2}]' WHERE id = 'cmma2ku730001ntub8wc2ytwu'; -- Mojito
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3ji0005o1nw11qwqv97","name":"Vodka","amount":2,"pourOrder":1},{"bottleId":"cmmgep3pr00iwo1nw8lhyzmpp","name":"Lime Juice","amount":0.5,"pourOrder":1}]' WHERE id = 'cmma2ku8l0001ack961ip3vpk'; -- Moscow Mule
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3jm000ao1nwvx8o3tp6","name":"Mezcal","amount":0.75,"pourOrder":1},{"bottleId":"cmmhaha03000012p6betp0tjy","name":"Yellow Chartreuse","amount":0.75,"pourOrder":1},{"bottleId":"cmmgep3om00f8o1nwo3o2vrgk","name":"Aperol","amount":0.75,"pourOrder":1},{"bottleId":"cmmgep3pr00iwo1nw8lhyzmpp","name":"Lime Juice","amount":0.75,"pourOrder":2}]' WHERE id = 'cmmhaha0a000312p6l2qsc7qj'; -- Naked and Famous
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3je0001o1nwu7e8off1","name":"Gin","amount":1,"pourOrder":1},{"bottleId":"cmmgep3ol00f6o1nwinexd6jf","name":"Campari","amount":1,"pourOrder":1},{"bottleId":"cmmgep3mi0096o1nwz7p1ekwb","name":"Sweet Vermouth","amount":1,"pourOrder":1}]' WHERE id = 'cmma2kua80001numbbpc5b8iv'; -- Negroni
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3jr000io1nw2k85pm7x","name":"Bourbon","amount":2,"pourOrder":1},{"bottleId":"cmmgep3re00o4o1nwwvrma14j","name":"Angostura Aromatic Bitters","amount":0.25,"pourOrder":1}]' WHERE id = 'cmma2loyf000110vgl0qdd3gt'; -- Old Fashioned
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3jg0003o1nw2wl9z27o","name":"Tequila","amount":2,"pourOrder":1},{"bottleId":"cmmgep3pr00iwo1nw8lhyzmpp","name":"Lime Juice","amount":0.5,"pourOrder":1}]' WHERE id = 'cmma2kud30001125akr7wj2yd'; -- Paloma
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3k4001oo1nwellioomj","name":"Scotch Blended","amount":2,"pourOrder":1},{"bottleId":"cmmgep3pp00ioo1nwgfpska2u","name":"Lemon Juice","amount":0.75,"pourOrder":2},{"bottleId":"cmmhaha1w0000119gw5jinwru","name":"Honey-Ginger Syrup","amount":0.75,"pourOrder":2},{"bottleId":"cmmgep3jz0016o1nw91d4gbjl","name":"Scotch Single Malt","amount":0.25,"pourOrder":3}]' WHERE id = 'cmmhaha200002119gtv8g0p6x'; -- Penicillin
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3nl00c4o1nww1xrrxtp","name":"Pisco","amount":2,"pourOrder":1},{"bottleId":"cmmgep3pr00iwo1nw8lhyzmpp","name":"Lime Juice","amount":1,"pourOrder":1},{"bottleId":"cmmgep3qv00mgo1nwc960yavi","name":"Simple Syrup","amount":0.75,"pourOrder":1},{"bottleId":"cmmgep3re00o4o1nwwvrma14j","name":"Angostura Aromatic Bitters","amount":0.1,"pourOrder":1}]' WHERE id = 'cmma3hf3k000cs5w11oprrwgb'; -- Pisco Sour
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3lc005io1nw328zeizv","name":"White Rum","amount":2,"pourOrder":1},{"bottleId":"cmmgep3pu00j4o1nwasmem21y","name":"Pineapple Juice","amount":1.5,"pourOrder":1},{"bottleId":"fix_coconut_cream_001","name":"Coconut Cream","amount":1,"pourOrder":1}]' WHERE id = 'cmma2lp1f0001dbxd5gd335uh'; -- Piña Colada
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3je0001o1nwu7e8off1","name":"Gin","amount":2,"pourOrder":1},{"bottleId":"cmmgep3pp00ioo1nwgfpska2u","name":"Lemon Juice","amount":1,"pourOrder":1},{"bottleId":"cmmgep3pr00iwo1nw8lhyzmpp","name":"Lime Juice","amount":0.5,"pourOrder":1},{"bottleId":"cmmgep3qv00mgo1nwc960yavi","name":"Simple Syrup","amount":0.5,"pourOrder":1},{"bottleId":"cmmgep3qs00m6o1nwtg9vgg41","name":"Soda Water","amount":1,"pourOrder":2},{"bottleId":"fix_cream_001","name":"Cream","amount":1,"pourOrder":1}]' WHERE id = 'cmma41kf50001vaq9v5l039dn'; -- Ramos Gin Fizz
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3jz0016o1nw91d4gbjl","name":"Scotch Single Malt","amount":1.5,"pourOrder":1},{"bottleId":"fix_drambuie_001","name":"Drambuie","amount":0.75,"pourOrder":1}]' WHERE id = 'cmma6357d0004bkfv02onzpyh'; -- Rusty Nail
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3kc002co1nwtkpunj35","name":"Rye Whiskey","amount":2,"pourOrder":1},{"bottleId":"cmmgep3qv00mgo1nwc960yavi","name":"Simple Syrup","amount":0.25,"pourOrder":1},{"bottleId":"cmmgep3re00o4o1nwwvrma14j","name":"Angostura Aromatic Bitters","amount":0.031,"pourOrder":1}]' WHERE id = 'cmma50t3g0006xhvus9uh1d3n'; -- Sazerac
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3ji0005o1nw11qwqv97","name":"Vodka","amount":2,"pourOrder":1},{"bottleId":"cmmgep3pm00ieo1nwl3fd8emz","name":"Orange Juice","amount":4,"pourOrder":2}]' WHERE id = 'cmmhac8li0001o61zqee69n8f'; -- Screwdriver
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3ne00bko1nwejs5q4yh","name":"Cognac","amount":2,"pourOrder":1},{"bottleId":"cmmgep3nx00d4o1nwgbkk3giv","name":"Triple Sec","amount":1,"pourOrder":1},{"bottleId":"cmmgep3pp00ioo1nwgfpska2u","name":"Lemon Juice","amount":1,"pourOrder":1}]' WHERE id = 'cmma2lp2z0001u70ebf86j775'; -- Sidecar
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3je0001o1nwu7e8off1","name":"Gin","amount":1.5,"pourOrder":1},{"bottleId":"fix_cherry_liqueur_001","name":"Cherry Liqueur","amount":0.5,"pourOrder":1},{"bottleId":"cmmgep3nw00d2o1nw8z1ed32x","name":"Cointreau","amount":0.5,"pourOrder":1},{"bottleId":"fix_benedictine_001","name":"Benedictine","amount":0.5,"pourOrder":1},{"bottleId":"cmmgep3pu00j4o1nwasmem21y","name":"Pineapple Juice","amount":1,"pourOrder":1},{"bottleId":"cmmgep3pr00iwo1nw8lhyzmpp","name":"Lime Juice","amount":0.5,"pourOrder":1},{"bottleId":"cmmgep3re00o4o1nwwvrma14j","name":"Angostura Aromatic Bitters","amount":0.05,"pourOrder":1}]' WHERE id = 'cmma461yt000fpqdwuzf1liny'; -- Singapore Sling
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3m1007oo1nwnu0bwiwk","name":"Tequila","amount":1.5,"pourOrder":1},{"bottleId":"cmmgep3pm00ieo1nwl3fd8emz","name":"Orange Juice","amount":3,"pourOrder":2},{"bottleId":"cmmgep3qx00moo1nwitbb1r9z","name":"Grenadine","amount":0.5,"pourOrder":3}]' WHERE id = 'cmmhaha7z0001in04nltah82j'; -- Tequila Sunrise
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3je0001o1nwu7e8off1","name":"Gin","amount":2,"pourOrder":1},{"bottleId":"cmmgep3pp00ioo1nwgfpska2u","name":"Lemon Juice","amount":1,"pourOrder":1},{"bottleId":"cmmgep3qs00m6o1nwtg9vgg41","name":"Soda Water","amount":1,"pourOrder":2}]' WHERE id = 'cmma2kuhl000112nv57w9mdu0'; -- Tom Collins
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3je0001o1nwu7e8off1","name":"Gin","amount":3,"pourOrder":1},{"bottleId":"cmmgep3ji0005o1nw11qwqv97","name":"Vodka","amount":1,"pourOrder":1},{"bottleId":"cmmgep3oq00fmo1nw1selym53","name":"Lillet Blanc","amount":0.5,"pourOrder":1}]' WHERE id = 'cmma2lp5y00016yonuw6ffth9'; -- Vesper Martini
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3jr000io1nw2k85pm7x","name":"Bourbon","amount":2,"pourOrder":1},{"bottleId":"cmmgep3pp00ioo1nwgfpska2u","name":"Lemon Juice","amount":1,"pourOrder":1}]' WHERE id = 'cmma2kukk00018dbab5smqm2i'; -- Whiskey Sour
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3ji0005o1nw11qwqv97","name":"Vodka","amount":2,"pourOrder":1},{"bottleId":"cmmgep3nz00dco1nwwr7os5qm","name":"Coffee Liqueur","amount":1,"pourOrder":1},{"bottleId":"fix_cream_001","name":"Cream","amount":1,"pourOrder":2}]' WHERE id = 'cmma58auo0004w3jwagvezjiw'; -- White Russian
UPDATE Cocktail SET recipe = '[{"bottleId":"cmmgep3lc005io1nw328zeizv","name":"White Rum","amount":1,"pourOrder":1},{"bottleId":"cmmgep3lj0064o1nwcank12o2","name":"Dark Rum","amount":1,"pourOrder":1},{"bottleId":"cmmgep3lt006yo1nwg8j7yrek","name":"Overproof Rum","amount":1,"pourOrder":2},{"bottleId":"cmmgep3pr00iwo1nw8lhyzmpp","name":"Lime Juice","amount":0.75,"pourOrder":1},{"bottleId":"cmmgep3pu00j4o1nwasmem21y","name":"Pineapple Juice","amount":0.5,"pourOrder":1},{"bottleId":"cmmgep3q400k0o1nw4sneladz","name":"Grapefruit Juice","amount":0.5,"pourOrder":1},{"bottleId":"fix_apricot_liqueur_001","name":"Apricot Liqueur","amount":0.5,"pourOrder":1},{"bottleId":"cmmgep3qx00moo1nwitbb1r9z","name":"Grenadine","amount":0.25,"pourOrder":1}]' WHERE id = 'cmma4fc2v000fo4147pg8q579'; -- Zombie

-- ── Verification query (should return 0 rows after migration) ───────────
-- SELECT c.name, jt.bottleId
-- FROM Cocktail c
--   JOIN JSON_TABLE(c.recipe, '$[*]' COLUMNS(bottleId VARCHAR(255) PATH '$.bottleId')) jt
--   LEFT JOIN Bottle b ON b.id = jt.bottleId
-- WHERE jt.bottleId IS NOT NULL AND b.id IS NULL;
